package app.suprsend.event

import androidx.annotation.AnyThread
import app.suprsend.base.LocalStorage
import app.suprsend.base.SSConstants
import app.suprsend.log.Logger
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

/**
 * A single stored entry: the user payload (already serialized as a JSON string) plus the
 * store-owned identity used to uniquely address it from the moment it is inserted.
 *
 * The id is generated by the store on insert (callers do not supply it) so we never depend
 * on any field inside the user payload to identify the entry. This makes the store usable
 * for any kind of payload.
 *
 * `payloadJson` is a String — it is wire-ready (can be passed straight to an HTTP body) and
 * cannot be mutated by callers after it leaves the store.
 */
internal data class Payload(
    val id: String,
    val payloadJson: String
)

/**
 * Persists arbitrary JSON payloads in SharedPreferences while the device is offline.
 *
 * On insert, every user payload is wrapped as:
 *   `{ "id": "<uuid>", "payload": <userJson> }`
 *
 * The wrapper id is generated inside [store] and returned to the caller. All read / remove
 * operations are addressed by that id so producers and the consumer agree on identity
 * regardless of what is inside the user payload.
 *
 * Storage shape on disk (single SharedPreferences string keyed by
 * [SSConstants.OFFLINE_NOTIFICATION_EVENTS]):
 *
 *   `[ {id, payload}, {id, payload}, ... ]`
 *
 * Concurrency model:
 *  - Multiple producers (FCM push, redirection activity, dismiss receiver, etc.) may call
 *    [store] concurrently. A single consumer ([EventFlushHandler]) drains via
 *    [peek] + [removeById].
 *  - Every mutation is guarded by a single intrinsic lock so each operation is atomic and
 *    durably committed before the next caller proceeds.
 *  - The consumer MUST address removals by envelope id ([removeById]) so a producer-driven
 *    capacity eviction during the consumer's HTTP call cannot silently delete a fresh
 *    un-flushed payload — `removeById` becomes a no-op if the targeted entry was already
 *    evicted, whereas any positional removal would silently target an unrelated payload.
 *  - [peek] returns a [Payload] whose `payloadJson` is a freshly-parsed detached copy, so
 *    callers may use it outside the lock without seeing concurrent mutations.
 */
internal object PayloadOfflineStore {

    private const val TAG = "payload_offline_store"

    private const val KEY_ID = "id"
    private const val KEY_PAYLOAD = "payload"

    private val lock = Any()

    /**
     * Wrap [payloadJson] in a store-owned envelope, persist it, and return the freshly
     * generated id. If the queue is at capacity, the oldest entries are evicted first.
     */
    @AnyThread
    fun store(payloadJson: JSONObject): String {
        val id = UUID.randomUUID().toString()
        val wrapper = JSONObject().apply {
            put(KEY_ID, id)
            put(KEY_PAYLOAD, payloadJson)
        }
        val newSize = synchronized(lock) {
            try {
                val current = readArray()
                while (current.length() >= SSConstants.OFFLINE_NOTIFICATION_EVENTS_MAX_COUNT) {
                    current.remove(0)
                }
                current.put(wrapper)
                writeArray(current)
                current.length()
            } catch (e: Exception) {
                Logger.e(TAG, "Failed to store payload", e)
                -1
            }
        }
        if (newSize >= 0) {
            Logger.i(TAG, "Stored payload $id. Total queued : $newSize")
        }
        return id
    }

    /**
     * Returns the oldest valid entry as a [Payload], or `null` if the queue is empty.
     * Malformed entries at the head are skipped silently — the caller never sees them.
     */
    @AnyThread
    fun peek(): Payload? {
        synchronized(lock) {
            val current = readArray()
            for (i in 0 until current.length()) {
                val parsed = parseEntry(current.optJSONObject(i)) ?: continue
                return parsed
            }
            return null
        }
    }

    /**
     * Number of entries currently persisted (including any that fail to parse — they still
     * take up space until they get evicted or rewritten).
     */
    @AnyThread
    fun size(): Int {
        synchronized(lock) {
            return readArray().length()
        }
    }

    /**
     * Removes the entry whose envelope id matches [id]. Returns `true` if an entry was
     * removed, `false` if no entry with that id was found (e.g. because a producer evicted
     * it after the consumer peeked it).
     *
     * Safe primitive for the flush flow — robust to capacity-driven evictions that happen
     * between the consumer's [peek] and the subsequent remove.
     */
    @AnyThread
    fun removeById(id: String): Boolean {
        if (id.isBlank()) return false
        synchronized(lock) {
            try {
                val current = readArray()
                for (i in 0 until current.length()) {
                    val entry = current.optJSONObject(i) ?: continue
                    if (entry.optString(KEY_ID) == id) {
                        current.remove(i)
                        if (current.length() == 0) {
                            LocalStorage.remove(SSConstants.OFFLINE_NOTIFICATION_EVENTS)
                        } else {
                            writeArray(current)
                        }
                        return true
                    }
                }
                return false
            } catch (e: Exception) {
                Logger.e(TAG, "Failed to remove payload by id", e)
                return false
            }
        }
    }

    @AnyThread
    fun clear() {
        synchronized(lock) {
            LocalStorage.remove(SSConstants.OFFLINE_NOTIFICATION_EVENTS)
        }
    }

    private fun parseEntry(entry: JSONObject?): Payload? {
        entry ?: return null
        val id = entry.optString(KEY_ID)
        if (id.isNullOrBlank()) return null
        val payload = entry.optJSONObject(KEY_PAYLOAD) ?: return null
        return Payload(id, payload.toString())
    }

    private fun readArray(): JSONArray {
        val raw = LocalStorage.getValue(SSConstants.OFFLINE_NOTIFICATION_EVENTS)
        if (raw.isNullOrBlank()) return JSONArray()
        return try {
            JSONArray(raw)
        } catch (e: Exception) {
            Logger.e(TAG, "Corrupted offline payload store, resetting", e)
            LocalStorage.remove(SSConstants.OFFLINE_NOTIFICATION_EVENTS)
            JSONArray()
        }
    }

    private fun writeArray(array: JSONArray) {
        LocalStorage.setValue(SSConstants.OFFLINE_NOTIFICATION_EVENTS, array.toString())
    }
}
